### ISSUE TITLE
Issues w/ tutorial NEQ run

### ISSUE THREAD

**Issue by spadavec** [SimonBoothroyd/absolv#66]
I've tried running the NEQ example as outline in the documentation:

```python

from openmm import unit

from absolv.models import (
    NonEquilibriumPfrom openff.toolkit.typing.engines.smirnoff import ForceField
force_field = ForceField("openff-2.0.0.offxml")

from absolv.runners.equilibrium import NonEquilibriumRunner
NonEquilibriumRunner.setup(schema, force_field)rotocol,
    SwitchingProtocol,
    SimulationProtocol,
    State,
    System,
    TransferFreeEnergySchema
)
from absolv.runners.nonequilibrium import NonEquilibriumRunner
from openff.toolkit.typing.engines.smirnoff import ForceField

schema = TransferFreeEnergySchema(
    system=System(solutes={"CCO": 1}, solvent_a=None, solvent_b={"O": 895}),
    # Define the state that the calculation will be performed at.
    state=State(temperature=298.15 * unit.kelvin, pressure=1.0 * unit.atmosphere),
    # Define the alchemical pathway to transform the solute along in vacuum ('solvent_a')
    # and water ('solvent_b')
    alchemical_protocol_a=NonEquilibriumProtocol(
        production_protocol=SimulationProtocol(
            n_steps_per_iteration=6250,
            n_iterations=160,
            timestep=2.0 * unit.femtoseconds
        ),
        switching_protocol=SwitchingProtocol(
            n_electrostatic_steps=60,
            n_steps_per_electrostatic_step=100,
            n_steric_steps=0,
            n_steps_per_steric_step=0,
            timestep=2.0*unit.femtoseconds
        )
    ),
    alchemical_protocol_b=NonEquilibriumProtocol(
        production_protocol=SimulationProtocol(
            n_steps_per_iteration=6250,
            n_iterations=160,
            timestep=2.0 * unit.femtoseconds
        ),
        switching_protocol=SwitchingProtocol(
            # Annihilate the electrostatic interactions over the first 12 ps
            n_electrostatic_steps=60,
            n_steps_per_electrostatic_step=100,
            # followed by decoupling the vdW interactions over the next 38 ps
            n_steric_steps=190,
            n_steps_per_steric_step=100,
        )
    )
)

force_field = ForceField("openff-2.0.0.offxml")
NonEquilibriumRunner.setup(schema, force_field)
```

However, the above gives the error: 

```
Traceback (most recent call last):
  File "testRun.py", line 52, in <module>
    NonEquilibriumRunner.setup(schema, force_field)
  File "/home/spadavec/itx/research_projects/absolv/absolv/runners/_runners.py", line 171, in setup
    cls._setup_solvent(
  File "/home/spadavec/itx/research_projects/absolv/absolv/runners/_runners.py", line 96, in _setup_solvent
    topology, coordinates = PACKMOLCoordinateFactory.generate(components)
  File "/home/spadavec/itx/research_projects/absolv/absolv/factories/coordinate.py", line 147, in generate
    box_size = cls._approximate_box_size_by_density(components, target_density)
  File "/home/spadavec/itx/research_projects/absolv/absolv/factories/coordinate.py", line 68, in _approximate_box_size_by_density
    volume += molecule_volume * count
  File "/home/spadavec/miniconda3/envs/absolv2/lib/python3.8/site-packages/openmm/unit/quantity.py", line 235, in __add__
    raise TypeError('Cannot add two quantities with incompatible units "%s" and "%s".' % (self.unit, other.unit))
TypeError: Cannot add two quantities with incompatible units "angstrom**3" and "mole*milliliter/gram".
```

Is there something I need to change? I should also note in the documentation, the NEQ example needs to change the following line(s):

from
```python
from absolv.runners.equilibrium import NonEquilibriumRunner
```
to
```python
from absolv.runners.nonequilibrium import NonEquilibriumRunner
```
and `SwitchingProtocol` is never imported from `absolv.models`

Cheers

**Comment by SimonBoothroyd** [comment]
Thanks for reporting this, and sorry it took so long to see it!

I've spent some time re-writing the framework (#67), and this issue should hopefully be fixed in the new version that will be released shortly.
